version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/rundit/backend"
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres
    ports:
      - "7654:5432"
    environment:
      POSTGRES_PASSWORD: dbpasswd